// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9txG910vGx5tjXD96plrcpqYs2F5Fmio',
    appId: '1:282188392920:web:e97364323797b0e802aaad',
    messagingSenderId: '282188392920',
    projectId: 'mentorly-66d07',
    authDomain: 'mentorly-66d07.firebaseapp.com',
    databaseURL: 'https://mentorly-66d07-default-rtdb.firebaseio.com',
    storageBucket: 'mentorly-66d07.firebasestorage.app',
    measurementId: 'G-BVVVBB8BWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvItHyHz6Zju65VkRnyLStcdhdsaFKpWI',
    appId: '1:282188392920:android:3d405aa2334acd9e02aaad',
    messagingSenderId: '282188392920',
    projectId: 'mentorly-66d07',
    databaseURL: 'https://mentorly-66d07-default-rtdb.firebaseio.com',
    storageBucket: 'mentorly-66d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfVvYm_MSsxEzUTTTbmNtGuKRxpkzATbQ',
    appId: '1:282188392920:ios:6b5210310741817302aaad',
    messagingSenderId: '282188392920',
    projectId: 'mentorly-66d07',
    databaseURL: 'https://mentorly-66d07-default-rtdb.firebaseio.com',
    storageBucket: 'mentorly-66d07.firebasestorage.app',
    iosBundleId: 'com.example.mentorly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfVvYm_MSsxEzUTTTbmNtGuKRxpkzATbQ',
    appId: '1:282188392920:ios:6b5210310741817302aaad',
    messagingSenderId: '282188392920',
    projectId: 'mentorly-66d07',
    databaseURL: 'https://mentorly-66d07-default-rtdb.firebaseio.com',
    storageBucket: 'mentorly-66d07.firebasestorage.app',
    iosBundleId: 'com.example.mentorly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9txG910vGx5tjXD96plrcpqYs2F5Fmio',
    appId: '1:282188392920:web:bfc9ee8c68503c1a02aaad',
    messagingSenderId: '282188392920',
    projectId: 'mentorly-66d07',
    authDomain: 'mentorly-66d07.firebaseapp.com',
    databaseURL: 'https://mentorly-66d07-default-rtdb.firebaseio.com',
    storageBucket: 'mentorly-66d07.firebasestorage.app',
    measurementId: 'G-Y3VBP9PCWF',
  );
}
